defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

#####################################
n_objs: 3
n_vars: 100
# To be assigned later
size:

# Range from which to sample the objective coefficients
obj_lb: 1
obj_ub: 100

# Range from which to sample the constraint coefficients
cons_lb: 1
cons_ub: 1000

n_train: 1000
n_test: 100
n_val: 100
seed: 7

#####################################
# Knapsack Problem
correlated: false

#####################################
# Independent Set
graph_type: stidsen
# 2, 4, 8, 16
attach: 4
# Average number of variables per constraint
vars_per_con: 10

hydra:
  output_subdir: null
  run:
    dir: .
